/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { IERC20 } from "./IERC20";
export type { JunkCoinDepositedERC20 } from "./JunkCoinDepositedERC20";
export type { JunkCoinERC20 } from "./JunkCoinERC20";
export type { Junkeng } from "./Junkeng";

export { ERC20__factory } from "./factories/ERC20__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
export { JunkCoinDepositedERC20__factory } from "./factories/JunkCoinDepositedERC20__factory";
export { JunkCoinERC20__factory } from "./factories/JunkCoinERC20__factory";
export { Junkeng__factory } from "./factories/Junkeng__factory";
